// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add_nikki_today() {
  return window['go']['main']['App']['Add_nikki_today']();
}

export function Get_dir_fnames(arg1) {
  return window['go']['main']['App']['Get_dir_fnames'](arg1);
}

export function Get_nikki(arg1) {
  return window['go']['main']['App']['Get_nikki'](arg1);
}

export function Get_nikki_count() {
  return window['go']['main']['App']['Get_nikki_count']();
}

export function Get_setting() {
  return window['go']['main']['App']['Get_setting']();
}

export function Load_nikki() {
  return window['go']['main']['App']['Load_nikki']();
}

export function Load_nikki_content() {
  return window['go']['main']['App']['Load_nikki_content']();
}

export function Load_setting() {
  return window['go']['main']['App']['Load_setting']();
}

export function Parse_nikki_file_fname(arg1) {
  return window['go']['main']['App']['Parse_nikki_file_fname'](arg1);
}

export function Select_Nikki_dir_Dialog() {
  return window['go']['main']['App']['Select_Nikki_dir_Dialog']();
}

export function Set_nikki(arg1, arg2) {
  return window['go']['main']['App']['Set_nikki'](arg1, arg2);
}

export function Set_setting(arg1) {
  return window['go']['main']['App']['Set_setting'](arg1);
}

export function Write_nikki_file(arg1) {
  return window['go']['main']['App']['Write_nikki_file'](arg1);
}

export function Write_setting() {
  return window['go']['main']['App']['Write_setting']();
}
