// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Add_nikki_today():Promise<void>;

export function Check_Nikki_null():Promise<boolean>;

export function Get_dir_fnames(arg1:string):Promise<Array<string>>;

export function Get_nikki():Promise<Array<main.Nikki_t>>;

export function Get_nikki_by_index(arg1:number):Promise<main.Nikki_t>;

export function Get_nikki_length():Promise<number>;

export function Get_setting():Promise<main.Setting_t>;

export function Load_nikki():Promise<void>;

export function Load_setting():Promise<void>;

export function Loading_nikki_index(arg1:number):Promise<void>;

export function Parse_nikki_file(arg1:string):Promise<main.Nikki_t>;

export function Select_Nikki_dir_Dialog():Promise<string>;

export function Set_nikki(arg1:Array<main.Nikki_t>):Promise<void>;

export function Set_nikki_by_index(arg1:main.Nikki_t,arg2:number):Promise<void>;

export function Set_setting(arg1:main.Setting_t):Promise<void>;

export function Write_nikki_file(arg1:main.Nikki_t):Promise<void>;

export function Write_setting():Promise<void>;
