on:
  workflow_dispatch:
  push:
    tags:
      - '*'
      
name: Release
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.6'
      - name: apt-get update
        run: sudo apt-get update
      - name: add-apt-repository
        run: sudo add-apt-repository -y "deb http://gb.archive.ubuntu.com/ubuntu jammy main"
      - name: apt-get update
        run: sudo apt-get update
      - name: Install pkg for wails
        run: sudo apt-get install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev -y
      - name: Install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: wails build
        run: wails build -platform windows/amd64
      - name: cp README.md
        run: cp README.md build/bin
      - name: Rename build/bin
        working-directory: build
        run: mv bin nikki-book
      - name: Make zip file
        working-directory: build
        run: zip -r nikki-book-windows.zip nikki-book
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/nikki-book-windows.zip
