on:
  workflow_dispatch:
  push:
    tags:
      - '*'
name: Release
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.6'
      - name: Install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: wails build
        run: wails build -platform windows/amd64
      - name: cp README.md
        run: cp README.md build/bin
      - name: Make zip file
        run: zip -r nikki-book-windows.zip build/bin
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: nikki-book-windows.zip
