on:
  workflow_dispatch:
  push:

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.6'
      - name: apt update
        run: apt-get update
      - name: Install pkg for wails
        run: apt-get install libwebkit2gtk-4.0-dev libgtk-3-dev -y
      - name: Install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: wails build
        run: wails build
      - name: Test
        run: go test
